pluginManagement {
    def bbsPreferMirror = gradle.startParameter.projectProperties.getOrDefault("bbsPreferMirror", "false").toBoolean()
    def neoForgedOfficial = 'https://maven.neoforged.net/releases'
    def neoForgedMirror = 'https://cfproxy.sweatent.top/-----https://maven.neoforged.net/releases'

    repositories {
        gradlePluginPortal()
        if (bbsPreferMirror) {
            maven {
                name = 'NeoForged Mirror Primary'
                url = neoForgedMirror
            }
            maven {
                name = 'NeoForged Official Fallback'
                url = neoForgedOfficial
            }
        } else {
            maven {
                name = 'NeoForged Official Primary'
                url = neoForgedOfficial
            }
            maven {
                name = 'NeoForged Mirror Fallback'
                url = neoForgedMirror
            }
        }
        mavenCentral()
    }

    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'net.neoforged.gradle.userdev' && requested.version != null) {
                useModule("net.neoforged.gradle:userdev:${requested.version}")
            }
        }
    }
}

rootProject.name = "BBS mod"
